name: Flask CI/CD with EC2

on:
  push:
    branches:
      - staging
  release:
    types: [created]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: pytest

  deploy-staging:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to EC2 (Staging)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
<<<<<<< HEAD
            cd /home/ubuntu/Jenkins-githubAction-python-project
            python3 -m venv venv
            source venv/bin/activate
            
            pip install --upgrade pip
            pip install -r requirements.txt
            
            pkill -f app.py || true
            nohup venv/bin/python app.py > app.log 2>&1 &
=======
            sudo apt update && sudo apt upgrade -y
            git clone https://github.com/saiyedin786/Jenkins-githubAction-python-project.git
            cd Jenkins-githubAction-python-project.git
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install gunicorn
            gunicorn --bind 0.0.0.0:8000 app:app
            sudo nginx -t
            sudo systemctl restart nginx
>>>>>>> f60bfe492ffadcfd439a74793f23134f0847477e
  deploy-production:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Deploy to EC2 (Production)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_APP_DIR }} || exit 1
            git pull origin main
            pip3 install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &
